DROP TABLE IF EXISTS pairs;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS nouns;
DROP TABLE IF EXISTS adjectives;
DROP TABLE IF EXISTS requests;

CREATE TABLE pairs(
  id SERIAL4 PRIMARY KEY,
  digits VARCHAR(30) NOT NULL,
  time_stamp TIMESTAMP NOT NULL,
  adjective_1_id INTEGER NOT NULL,
  noun_1_id INTEGER NOT NULL,
  adjective_2_id INTEGER NOT NULL,
  noun_2_id INTEGER NOT NULL,
  access_count INTEGER
);

CREATE TABLE nouns(
  id SERIAL4 PRIMARY KEY,
  word VARCHAR(16) NOT NULL
);

CREATE TABLE adjectives(
  id SERIAL4 PRIMARY KEY,
  word VARCHAR(16) NOT NULL
);
